### PR TITLE
Increase test coverage

### PR DESCRIPTION
**Pull request by jmrodri**
Refactored the handler to be more testable by allowing you to pass in a map[string]string as a third argument.

### CODE REVIEW

**Comment by jmrodri** [comment]
@ernelson https://github.com/gorilla/mux/blob/master/mux.go#L352

**Comment by eriknelson** [comment]
ACK pending deployment test

**Comment by jmrodri** [comment]
catalog test
```
[2017-03-22T09:43:34.708-04:00] [DEBUG] Loading image list for org: [ ansibleapp ]
[2017-03-22T09:43:36.526-04:00] [DEBUG] Trying to load ansibleapp/ansible-service-broker-asb
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/etherpad-ansibleapp-etherpad
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/etherpad-ansibleapp-mariadb
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/etherpad-ansibleapp-nginx
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/nave-centos-mariadb
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/nave-centos-mariadb-vessel
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/fusor-guestbook-ansibleapp-main
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/elk-ansibleapp-elasticsearch
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/ansibleapp-base
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/nave-centos-vessel-base
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/etherpad-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/ansible-service-broker-etcd
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/elk-ansibleapp-logstash
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/elk-ansibleapp-kibana
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/wordpress-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/elk-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/miq-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/wordpress-ansibleapp-wordpress
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/galera-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/wordpress-ansibleapp-db
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/wordpress-db
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/wordpress-wordpress
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/nave-centos-vessel
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/galera-ansibleapp-mariadb-2
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/galera-ansibleapp-mariadb-3
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/galera-ansibleapp-mariadb-1
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/centos-nave-base
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/ansible-service-broker-ansibleapp
[2017-03-22T09:43:36.527-04:00] [DEBUG] Trying to load ansibleapp/fusor-guestbook-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/eriks-etherpad-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/wordpress-ansibleapp-mariadb
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/mongodb-ansibleapp-mongodb
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/mongodb-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/miq-ansibleapp-miq-postgresql
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/miq-ansibleapp-miq-app
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/miq-ansibleapp-miq-memcached
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/external-mlab-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/pulp-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/wordpress-ha-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/postgresql-ansibleapp
[2017-03-22T09:43:36.528-04:00] [DEBUG] Trying to load ansibleapp/foreman-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] Found ansibleapps:
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/wordpress-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/wordpress-ha-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/foreman-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/ansible-service-broker-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/mongodb-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/galera-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/pulp-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/external-mlab-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/miq-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/etherpad-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/fusor-guestbook-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/postgresql-ansibleapp
[2017-03-22T09:43:37.687-04:00] [INFO] docker://ansibleapp/eriks-etherpad-ansibleapp
```

**Comment by jmrodri** [comment]
PROVISION EXTERNAL MLAB
---------
```
[2017-03-22T09:45:09.419-04:00] [NOTICE] ============================================================
[2017-03-22T09:45:09.42-04:00] [NOTICE]                        PROVISIONING                         
[2017-03-22T09:45:09.42-04:00] [NOTICE] ============================================================
[2017-03-22T09:45:09.42-04:00] [NOTICE] Spec.Id: 071f3645-7189-4808-b9c2-2d29c143e80d
[2017-03-22T09:45:09.42-04:00] [NOTICE] Spec.Name: ansibleapp/external-mlab-ansibleapp
[2017-03-22T09:45:09.42-04:00] [NOTICE] Spec.Description: Bindable ansibleapp shim for external mlab mongodb database
[2017-03-22T09:45:09.42-04:00] [NOTICE] Parameters: &map[acct_one_pass:dog8one port:63699 ip:54.92.163.34 db:fusor_guestbook_db binding_key:zeusproject acct_one_user:duder_one project_name:zeusproject acct_two_user:duder_two acct_two_pass:dog8two]
[2017-03-22T09:45:09.42-04:00] [NOTICE] ============================================================
[2017-03-22T09:45:56.519-04:00] [DEBUG] Running OC run...
[2017-03-22T09:45:56.519-04:00] [DEBUG] clusterConfig:
[2017-03-22T09:45:56.519-04:00] [DEBUG] target: [ 10.1.2.2:8443 ]
[2017-03-22T09:45:56.519-04:00] [DEBUG] user: [ admin ]
[2017-03-22T09:45:56.519-04:00] [DEBUG] password:[ admin ]
[2017-03-22T09:45:56.519-04:00] [DEBUG] image:[ ansibleapp/external-mlab-ansibleapp ]
[2017-03-22T09:45:56.519-04:00] [DEBUG] action:[ provision ]
[2017-03-22T09:45:56.519-04:00] [DEBUG] params:[ {"acct_one_pass":"dog8one","acct_one_user":"duder_one","acct_two_pass":"dog8two","acct_two_user":"duder_two","binding_key":"zeusproject","db":"fusor_guestbook_db","ip":"54.92.163.34","port":"63699","project_name":"zeusproject"} ]
[2017-03-22T09:45:56.661-04:00] [INFO] pod "aa-a4cfa605-36ff-4a48-a4bd-8bfb50f279a6" created
```

**Comment by jmrodri** [comment]
BINDING CREATED
-------
```
[2017-03-22T09:46:45.03-04:00] [NOTICE] ============================================================
[2017-03-22T09:46:45.031-04:00] [NOTICE]                        BINDING                              
[2017-03-22T09:46:45.031-04:00] [NOTICE] ============================================================
[2017-03-22T09:46:45.031-04:00] [NOTICE] Parameters: &map[provision_params:map[project_name:zeusproject acct_one_pass:dog8one acct_two_user:duder_two binding_key:zeusproject db:fusor_guestbook_db ip:54.92.163.34 port:63699 acct_one_user:duder_one acct_two_pass:dog8two] bind_params:map[user:duder_one]]
[2017-03-22T09:46:45.031-04:00] [NOTICE] ============================================================
[2017-03-22T09:46:46.032-04:00] [DEBUG] Running OC run...
[2017-03-22T09:46:46.032-04:00] [DEBUG] clusterConfig:
[2017-03-22T09:46:46.033-04:00] [DEBUG] target: [ 10.1.2.2:8443 ]
[2017-03-22T09:46:46.033-04:00] [DEBUG] user: [ admin ]
[2017-03-22T09:46:46.033-04:00] [DEBUG] password:[ admin ]
[2017-03-22T09:46:46.033-04:00] [DEBUG] image:[ ansibleapp/external-mlab-ansibleapp ]
[2017-03-22T09:46:46.033-04:00] [DEBUG] action:[ bind ]
[2017-03-22T09:46:46.033-04:00] [DEBUG] params:[ {"bind_params":{"user":"duder_one"},"provision_params":{"acct_one_pass":"dog8one","acct_one_user":"duder_one","acct_two_pass":"dog8two","acct_two_user":"duder_two","binding_key":"zeusproject","db":"fusor_guestbook_db","ip":"54.92.163.34","port":"63699","project_name":"zeusproject"}} ]
[2017-03-22T09:46:46.219-04:00] [INFO] {pod "aa-6bfe9485-5a0f-48fd-9971-bdf8452f7e6f" created
}
```

**Comment by jmrodri** [comment]
PROVISION WITH BINDING
--------
```
[2017-03-22T09:47:07.62-04:00] [NOTICE] ============================================================
[2017-03-22T09:47:07.621-04:00] [NOTICE]                        PROVISIONING                         
[2017-03-22T09:47:07.621-04:00] [NOTICE] ============================================================
[2017-03-22T09:47:07.621-04:00] [NOTICE] Spec.Id: 35ead4e8-cf1f-4909-bb1b-b981f4eb3142
[2017-03-22T09:47:07.621-04:00] [NOTICE] Spec.Name: ansibleapp/fusor-guestbook-ansibleapp
[2017-03-22T09:47:07.621-04:00] [NOTICE] Spec.Description: A mongo backed guestbook in node
[2017-03-22T09:47:07.621-04:00] [NOTICE] Parameters: &map[mongo_db:fusor_guestbook_db mongo_pass:dog8one project_name:zeusproject mongo_user:duder_one binding_key:ZEUSPROJECT]
[2017-03-22T09:47:07.621-04:00] [NOTICE] ============================================================
[2017-03-22T09:47:10.376-04:00] [DEBUG] Running OC run...
[2017-03-22T09:47:10.376-04:00] [DEBUG] clusterConfig:
[2017-03-22T09:47:10.376-04:00] [DEBUG] target: [ 10.1.2.2:8443 ]
[2017-03-22T09:47:10.376-04:00] [DEBUG] user: [ admin ]
[2017-03-22T09:47:10.376-04:00] [DEBUG] password:[ admin ]
[2017-03-22T09:47:10.376-04:00] [DEBUG] image:[ ansibleapp/fusor-guestbook-ansibleapp ]
[2017-03-22T09:47:10.377-04:00] [DEBUG] action:[ provision ]
[2017-03-22T09:47:10.377-04:00] [DEBUG] params:[ {"binding_key":"ZEUSPROJECT","mongo_db":"fusor_guestbook_db","mongo_pass":"dog8one","mongo_user":"duder_one","project_name":"zeusproject"} ]
[2017-03-22T09:47:10.532-04:00] [INFO] pod "aa-c54f74b2-1794-4f6a-9519-6f7129e85edc" created
```

**Pull request merged**
