### PR TITLE
Replace get_images_from_org

### PR DESCRIPTION
**Pull request by rthallisey**
Currently we gather the list of images in a bash script. Let's pull that logic into the broker.
- Running the broker locally and in a cluster will use the same function instead
of looking for the script in <path>.
- One less file to track between runtime environments.
- Adding the logic to the broker will give us more flexibility to implement async pulls
in the future
- I finally figured out why my apbs were never loaded into the broker because we limit
the search to 100 just like the dockerhub!

TODO: Remove the param in the broker that accepts the script directory as a path. (The scripts
directory may still be used. In that case leave it in)

### CODE REVIEW

**Comment by jmrodri** [comment]
This needs rebasing now since I merged your other PR.

**Comment by jmrodri** [comment]
I was able to run this against our dockerhub registry, it worked.

**Comment by rthallisey** [comment]
@jmrodri rebased

**Comment by jmrodri** [comment]
TEST
-------
* make clean
* make install
* make run
* curl -X POST http://localhost:1338/v2/bootstrap

I was able to load up my docker hub org as well as ansibleplaybookbundle. 

**PASS**

**Pull request merged**
