### PR TITLE
Update glide.lock file

### LINKED ISSUE #100: Fix up glide.yaml to flatten dependecies
As part of make build we remove docker vendor dependency instead of having glide flatten it ```rm -rf ${GOPATH}/src/github.com/fusor/ansible-service-broker/vendor/github.com/docker/docker/vendor```.  We should get glide.yaml & glide.lock into good shape so we don't have to do this anymore and it avoid this coming up in the future.

### PR DESCRIPTION
**Pull request by rthallisey**
We need to update the glide.lock file to reflect the recent changes to glide.yaml.

Partially fixes #100

### CODE REVIEW

**Comment by jmrodri** [comment]
TEST INSTRUCTIONS
-------------------------
* add `-v` option to end of `@glide install` in the `vendor` target of the `Makefile`
* comment out the `rm -rf` of docker vendor directory from the `install` target

Then do the following:
1. remove the vendor directory: `rm -rf vendor`
2. clear out your `glide` cache: `glide cache-clear`
3. recreate the vendor directory: `make vendor`
4. rebuild broker: `make install`
5. PROFIT: :heavy_dollar_sign: :heavy_dollar_sign: :heavy_dollar_sign:

**Comment by rthallisey** [comment]
@jmrodri Did this work for you? I added in the stuff you mentioned in your test comment.

TBH I really think we should just remove glide.lock all together... Maybe in a follow up patch.

**Comment by jmrodri** [comment]
The glide.lock is there for a reason. The purpose is to lock down the actual deps. On rails and javascript files, we would check in the lock files. So I would vote no to *NOT* checking in the glide.lock file.

**Comment by rthallisey** [comment]
Ya but glide.yaml creates glide.lock based on the version that set in there for each pkg. I remember reading somewhere that we're not suppose to touch it. I'll check into it.

**Comment by jmrodri** [comment]
PROFIT: :heavy_dollar_sign: :heavy_dollar_sign: :heavy_dollar_sign: 

The test past. I'll see why travis is having issues.

**Comment by jmrodri** [comment]
Fixed travis. Our travis script was doing a normal `glide install` outside the `Makefile`. So that was creating the vendor directory WITH the vendor subdirs. So when our new Makefile never ran the `glide install -v`. Now that this is fixed. I'll verify this PR tomorrow morning, don't want to commit it tonight.

**Pull request merged**
